directories:
  output: release
  buildResources: build
appId: com.example.app
productName: MyApp
copyright: Copyright © 2025
files:
  - filter:
      - dist/**/*
      - scr/**/*
      - dist-electron/**/*
      - electron/**/*
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
mac:
  category: public.app-category.utilities
electronVersion: 37.2.5
